site_name         : Dinis Cruz - Documents and Research
site_description  : Site for Dinis Cruz - Documents and Research
site_url          : https://docs.diniscruz.ai/
use_directory_urls: false


plugins:
  - search
  - awesome-pages
  - macros
  - custom-footer

extra_css:
  - styles/custom.css

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


theme:
  name: material
  custom_dir: overrides