[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
package-mode = false

[project]
name = "docs-diniscruz-ai"
version = "v0.3.106"
description = "Dinis Cruz - Documents and Research"
readme = "README.md"
authors = [{name = "Dinis Cruz", email = "dinis.cruz@owasp.org"}]
license = {file = "LICENSE"}
requires-python = ">=3.7"

[project.optional-dependencies]
docs = [
    # Core MkDocs and Material theme
    "mkdocs",
    "mkdocs-material",
    "pymdown-extensions",

    # Existing plugins
    "mkdocs-awesome-pages-plugin",
    "mkdocs-macros-plugin",

    # New recommended plugins
    "mkdocs-rss-plugin",
    #"mkdocs-tags-plugin",
    "mkdocs-git-revision-date-localized-plugin",
    "mkdocs-minify-plugin",

    # Optional but useful
    "mkdocs-redirects",
    "mkdocs-print-site-plugin",
    "mkdocs-mermaid2-plugin"
]

# pip install -e ".[docs]"
